config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "homes/about" => "homes#about", as: "about"
  resources :books, only: [ :create, :index, :show, :edit, :destroy]
  patch 'books/:id' => 'books#update', as: 'update_book'
  resources :users, only: [ :index, :show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_one_attached :image
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 1, maximum: 200 }
  
  def get_image
    if image.attached?
      image
    else
      'no_image.jpg'
    end
  end
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy

  
  has_one_attached :profile_image
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  
  # 投稿データの保存
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "投稿が成功しました"
      redirect_to '/books'
    else
      render :new
    end
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.new
    @books = Book.all
    @book = Book.find(params[:id])
  end
  
  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    book = Book.find(params[:id])
    book.update(book_params)
    flash[:notice] = "編集が成功しました"
    redirect_to book_path(book.id)
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  
  # 投稿データのストロングパラメータ
  private
  
  def book_params
    params.require(:book).permit(:title, :image, :body)
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  
  def index
    @users = User.all
    @book = Book.new
    @books = Book.all
  end
  
  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
  
  def is_matching_login_user
    user_id = params[:id].to_i
    unless user_id == current_user.id
      redirect_to books_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_userinfo.html.erb
<% books.each do |book| %>

<div>
    <main>
  <div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <img <%= image_tag book.user.get_profile_image(100,100) %>
      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <th></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <a class="btn btn-outline-secondary btn-block edit_user_88852" href="/users/88852/edit">
          <i class="fas fa-users-cog"></i>
        </a>
      </div>
      <form action="/books" accept-charset="UTF-8" method="post">
        <h2 class="mt-3">New book</h2>
        <% if @book.errors.any? %>
          <ul class="alert alert-danger" role="alert">
            <h6 class="alert-heading">
              <%= @book.errors.count %>件のエラーが発生しました
            </h6>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <%= form_with model: @book do |f| %>
        <div class="new_post">
          
          
          
          
          <label for="book_title">Title</label>
          <input class="form-control book_title" type="text" name="book[title]" id="title">
        </div>
        <div class="new_post">
          
          
          
          
          
          <label for="book_opinion">Opinion</label>
          <textarea class="form-control book_body" name="book[body]" id="body"></textarea>
        </div>
        <p></p>
        <div class="new_post">
          
          
          
          <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
        <% end %>
        </div>
      </form>
      </div>
  </div>
</div>
</main>
</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  
<h1>Editing Book</h1>

<%= form_with model: @book, url:update_book_path(@book.id), method: :patch do |f| %>

  <h4>タイトル</h4>
  <%= f.text_field :title %>
  
  <h4>本文</h4>
  <%= f.text_area :body %>
  
  <%= f.submit '保存' %>
  
<% end %>

    

    <%= link_to "Show", @book, class: "book_#{@book.id}" %>
    <%= link_to "Back", books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<%= render 'userinfo', books: @books %>
<mian>
  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
            <% @books.each do |book| %>
            <th>Title</th>
            <%= link_to book.title, "/books/#{book.id}" %>
            
            <th>Opinion</th>
            <%= book.body %>
            <% end %>
         </tr>
    </thead>
    </table>
  </div>
</mian>

app/views/books/new.html.erb
<main>
  <div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <img src="/app/assets/images/no_image.jpg">
      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <th></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <a class="btn btn-outline-secondary btn-block edit_user_88852" href="/users/88852/edit">
          <i class="fas fa-users-cog"></i>
        </a>
      </div>
      <form action="/books" accept-charset="UTF-8" method="post">
        <h2 class="mt-3">New book</h2>
        <% if @book.errors.any? %>
          <ul class="alert alert-danger" role="alert">
            <h6 class="alert-heading">
              <%= @book.errors.count %>件のエラーが発生しました
            </h6>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <%= form_with model: @book do |f| %>
        <div class="new_post">
          
          
          
          
          <label for="book_title">Title</label>
          <input class="form-control book_title" type="text" name="book[title]" id="title">
        </div>
        <div class="new_post">
          
          
          
          
          
          <label for="book_opinion">Opinion</label>
          <textarea class="form-control book_body" name="book[body]" id="body"></textarea>
        </div>
        <p></p>
        <div class="new_post">
          
          
          
          <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
        <% end %>
        </div>
      </form>
      </div>
  </div>
</div>
</main>
      
      

<mian>
<% @books.each do |book| %>
  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
            <th>Title</th>
            <span><%= book.title %></span>
            <th>Opinion</th>
         </tr>
    </thead>
    </table>
  </div>
<% end %>
</mian>

app/views/books/show.html.erb
<div>
  <%= flash[:notice] %>
</div>
<%= render 'userinfo', books: @books %>

<mian>

  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
            <% @books.each do |book| %>
            <th>Title</th>
            <%= book.title %>
            <th>Opinion</th>
            <%= book.body %>
            <% end %>
            <% if @book.user == current_user %>
              <%= link_to "編集", edit_book_path(@book) %>
              <%= link_to "削除", book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
            <% end %>
         </tr>
    </thead>
    </table>
  </div>

</mian>

app/views/homes/about.html.erb
<h1 class="text-center">Welcome to 📕Bookers!</h1>

app/views/homes/top.html.erb
<p></p>
<div class="container">
    <div class="top1">
        <div class="mx-auto col-10 col-sm-10 col-lg-10 col-xl-7">
            <h1>welcome to 📕
                <strong>Bookers</strong>
                !!
            </h1>
            <p>In 📕 <strong>Bookers</strong>,</p>
        </div>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
            <div class="row">
                <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
            </div>
            <div class="row">
                <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css">
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse show" id="navbarNavDropdown" style>
            <ul class="navbar-nav ml-auto">
              <li>
                <a class="nav-link text-light" href="/">
                    <i class="fas fa-home"></i>
                  HOME
                </a>
              </li>
              <li>
                <a class="nav-link text-light" href="/homes/about">
                    <i class="fas fa-link"></i>
                  ABOUT
                </a>
              </li>
  <% if user_signed_in? %>
              <li>
                <a class="nav-link text-light" href="/books/">
                  <i class="fas fa-book"></i>
                  BOOK
                </a>
              </li>
              <li>
                <a class="nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out">
                  <i class="fas fa-sign-out-alt"></i>
                  LOG OUT
                </a>
              </li>
              <li>
                <%= link_to 'マイページ', user_path(current_user.id) %>    
              </li>
  <% else %>
              <li>
                <a class="nav-link text-light" href="/users/sign_up">
                  <i class="fas fa-user-plus"></i>
                  SING UP
                </a>
              </li>
              <li>
                <a class="nav-link text-light" href="/users/sign_in">
                  <i class="fas fa-sign-in"></i>
                  LOG IN
                </a>
              </li>
  <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <label for="inputImage">ProfileImage</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>  
  <%= f.submit "変更を保存" %>
<% end %>

app/views/users/index.html.erb
<%= render 'books/userinfo', books: @books %>

<mian>
  <div class="col-md-8 offset-md-1">
    <h2>Users</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
            <% @users.each do |user| %>
            <th>Title</th>
            <%= user.name %>
            
            <th>Opinion</th>
           
            <% end %>
         </tr>
    </thead>
    </table>
  </div>
</mian>

app/views/users/show.html.erb
<%= render 'books/userinfo', books: @books %>
<div>
  <h3><%= @user.name %></h3>
  <%= image_tag @user.get_profile_image(100,100) %>
  <% if @user == user_signed_in? %>
    <p><%= link_to "プロフィール編集", edit_user_path(@user) %></p>
  <% end %>
</div>

<!-- ユーザーの投稿一覧 -->

<% @books.each do |book| %>
<div>
  <%= link_to book_path(book.id) do %>
    <%= image_tag book.get_image %>
  <% end %>
  <p>投稿ユーザー画像：<%= image_tag book.user.get_profile_image(100,100) %></p>
  <p>ショップ名：<%= book.title %></p>
  <p>説明：<%= book.body %></p>
  <p>ユーザーネーム：<%= book.user.name %></p>
</div>
<% end %>